name: Setup
description: Set up mise tools and install dependencies
runs:
  using: composite
  steps:
    - name: Set up mise
      uses: jdx/mise-action@v3
    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: pnpm-store-${{ runner.os }}-
    - name: Install
      shell: bash
      run: pnpm i
