openapi: "3.0.0"
info:
  version: 1.0.0
  title: Messages API
paths:
  /ingest:
    post:
      summary: >
        Client-side streaming operation which accepts a stream of messages to
        ingest and does not return any data to the client.
      operationId: ingestMessages
      requestBody:
        $ref: "#/components/requestBodies/Messages"
      responses:
        '204':
          description: Messages successfully ingested
  /repeat:
    post:
      summary: >
        Server-side streaming operation which repeats the request's message
        back to the client multiple times.
      operationId: repeatMessage
      parameters:
        - name: count
          in: query
          description: How many items to repeat the message
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          $ref: "#/components/responses/Messages"
  /echo:
    post:
      summary: >
        Bidirectional streaming operation which echos request messages back to
        the client.
      operationId: echoMessages
      requestBody:
        $ref: "#/components/requestBodies/Messages"
      responses:
        '200':
          $ref: "#/components/responses/Messages"
components:
  requestBodies:
    Messages:
      description: A stream of messages
      required: true
      content:
        application/json-seq:
          schema:
            $ref: "#/components/schemas/Message"
  responses:
    Messages:
      description: A stream of messages
      content:
        application/json-seq:
          schema:
            $ref: "#/components/schemas/Message"
  schemas:
    Message:
      type: object
      required: [contents]
      properties:
        contents:
          type: string
