openapi: "3.0.0"
info:
  version: 1.0.0
  title: Messages API
paths:
  /process:
    post:
      summary: >
        Operation which processes the request's messages, streaming responses
        on demand.
      operationId: processMessages
      requestBody:
        description: A list of messages
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageArray"
      responses:
        '200':
          description: >
            A collection of messages, both unary and streaming content types
            are supported.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageArray"
            application/json-seq:
              schema:
                $ref: "#/components/schemas/Message"
  /ingest:
    post:
      summary: >
        Client-side streaming operation which accepts a stream of messages to
        ingest and returns the total ingested content length.
      operationId: ingestMessages
      requestBody:
        $ref: "#/components/requestBodies/MessageStream"
      responses:
        '200':
          description: Messages successfully ingested
          content:
            application/json:
              schema:
                type: number
  /echo:
    post:
      summary: >
        Bidirectional streaming operation which echoes messages back to the
        client in real time.
      operationId: echoMessages
      requestBody:
        $ref: "#/components/requestBodies/MessageStream"
      responses:
        '200':
          description: A stream of messages
          content:
            application/json-seq:
              schema:
                $ref: "#/components/schemas/Message"
components:
  requestBodies:
    MessageStream:
      description: A stream of messages
      required: true
      content:
        application/json-seq:
          schema:
            $ref: "#/components/schemas/Message"
  schemas:
    Message:
      type: object
      required: [contents]
      properties:
        contents:
          type: string
    MessageArray:
      type: array
      items:
        $ref: "#/components/schemas/Message"
